/* Original reasoning puzzles. Game scores are not IQ estimates. */
'use strict';
(() => {
const BANK = [
{"id":"e-n1","level":"explorer","category":"Number patterns","question":"What comes next?","options":["14","15","16","18"],"answer":"15","explanation":"Add 3 each time: 3, 6, 9, 12, 15.","hint":"Compare neighboring numbers.","tokens":["3","6","9","12","?"],"prompt":""},
{"id":"e-n2","level":"explorer","category":"Number patterns","question":"What comes next?","options":["26","28","30","32"],"answer":"30","explanation":"The differences are 4, 6, 8, then 10. Adding 10 to 20 gives 30.","hint":"The gaps form a pattern of their own.","tokens":["2","6","12","20","?"],"prompt":""},
{"id":"e-n3","level":"explorer","category":"Number patterns","question":"What comes next?","options":["10","12","14","16"],"answer":"16","explanation":"Each number is twice the one before it. Twice 8 is 16.","hint":"Try multiplication instead of addition.","tokens":["1","2","4","8","?"],"prompt":""},
{"id":"e-v1","level":"explorer","category":"Symbol patterns","question":"Which arrow comes next?","options":["↑","→","↓","←"],"answer":"↑","explanation":"Each arrow turns 90 degrees clockwise. After left, the next arrow points up.","hint":"Follow the direction of rotation.","tokens":["↑","→","↓","←","?"],"prompt":""},
{"id":"e-v2","level":"explorer","category":"Symbol patterns","question":"Which letter comes next?","options":["H","I","J","K"],"answer":"I","explanation":"Skip one letter each time: A, C, E, G, I.","hint":"Think about the letters between the ones shown.","tokens":["A","C","E","G","?"],"prompt":""},
{"id":"e-v3","level":"explorer","category":"Symbol patterns","question":"Which symbol comes next?","options":["◇","●","■","▲"],"answer":"◇","explanation":"The two symbols alternate: diamond, circle, diamond, circle, diamond.","hint":"Look for a repeating pair.","tokens":["◇","●","◇","●","?"],"prompt":""},
{"id":"e-l1","level":"explorer","category":"Deduction","question":"Which statement must be true?","options":["Every device in Box A is green.","Every green object is a device.","Every sensor is in Box A.","No device in Box A is green."],"answer":"Every device in Box A is green.","explanation":"All devices in Box A are sensors, and every sensor in Box A is green. So every device in that box is green. The statements say nothing about green objects elsewhere.","hint":"Follow the statements in one direction; do not reverse them.","tokens":[],"prompt":"Every device in Box A is a sensor. Every sensor in Box A is green."},
{"id":"e-l2","level":"explorer","category":"Deduction","question":"Who is first in this line?","options":["Mara","Eli","Noor","It cannot be determined."],"answer":"Mara","explanation":"Mara is ahead of Eli, who is ahead of Noor. The order is Mara, Eli, Noor.","hint":"Arrange the three names in the stated order.","tokens":[],"prompt":"There are exactly three people. Mara is ahead of Eli. Eli is ahead of Noor."},
{"id":"e-l3","level":"explorer","category":"Deduction","question":"Which switch is on?","options":["A","B","C","None of them."],"answer":"C","explanation":"There are only three switches and exactly one is on. A and B are off, leaving C.","hint":"Eliminate the switches already ruled out.","tokens":[],"prompt":"Exactly one of three switches, A, B, and C, is on. A is off. B is off."},
{"id":"m-n1","level":"analyst","category":"Number patterns","question":"What comes next?","options":["29","31","33","35"],"answer":"33","explanation":"The gaps grow by 2: +4, +6, +8, then +10. So 23 + 10 = 33.","hint":"Write the differences between neighboring numbers.","tokens":["5","9","15","23","?"],"prompt":""},
{"id":"m-n2","level":"analyst","category":"Number patterns","question":"What comes next?","options":["45","46","47","49"],"answer":"47","explanation":"Multiply by 2, then add 1 each time. So 23 × 2 + 1 = 47.","hint":"Try the same two operations at every step.","tokens":["2","5","11","23","?"],"prompt":""},
{"id":"m-n3","level":"analyst","category":"Number patterns","question":"What comes next?","options":["25","27","29","31"],"answer":"29","explanation":"Each number after the first two is the sum of the two before it: 3 + 4 = 7, 4 + 7 = 11, 7 + 11 = 18, and 11 + 18 = 29.","hint":"Look back two positions, not just one.","tokens":["3","4","7","11","18","?"],"prompt":""},
{"id":"m-v1","level":"analyst","category":"Symbol patterns","question":"Which pair comes next?","options":["10N","10O","12O","12P"],"answer":"10O","explanation":"The numbers increase by 2. The letters advance by 3 places: C, F, I, L, O. The next pair is 10O.","hint":"Follow the number and letter patterns separately.","tokens":["2C","4F","6I","8L","?"],"prompt":""},
{"id":"m-v2","level":"analyst","category":"Symbol patterns","question":"What completes the third arrow pair?","options":["↑","→","↓","←"],"answer":"↑","explanation":"Within each pair, the second arrow points opposite the first. The pairs are up/down, right/left, then down/up.","hint":"Treat each neighboring pair as a unit.","tokens":["↑","↓","→","←","↓","?"],"prompt":"Read the arrows in pairs: positions 1–2, 3–4, and 5–6."},
{"id":"m-v3","level":"analyst","category":"Symbol patterns","question":"Which letter comes next?","options":["T","U","V","W"],"answer":"V","explanation":"There are two interleaved sequences: A, C, E move forward by 2; Z, X, V move backward by 2.","hint":"Separate the odd and even positions.","tokens":["A","Z","C","X","E","?"],"prompt":""},
{"id":"m-l1","level":"analyst","category":"Deduction","question":"Can we conclude that some calibrated devices are wireless?","options":["Yes, that must be true.","No calibrated devices can be wireless.","Every wireless device is calibrated.","There is not enough information."],"answer":"There is not enough information.","explanation":"The wireless devices could be among the calibrated devices, or they could be a different part of the logged group. Both possibilities fit the statements.","hint":"Two groups can overlap a third group without overlapping each other.","tokens":[],"prompt":"All calibrated devices are logged. Some logged devices are wireless."},
{"id":"m-l2","level":"analyst","category":"Deduction","question":"Which ordering is guaranteed?","options":["W finishes before Z.","Y finishes before Z.","Z finishes before Y.","X finishes before W."],"answer":"W finishes before Z.","explanation":"W is before X, and Z is after X. Therefore W is before Z. The information does not determine the order of Y and Z.","hint":"Draw only the ordering relationships that are given.","tokens":[],"prompt":"Four tasks are W, X, Y, and Z. W finishes before X. X finishes before Y. Z finishes after X."},
{"id":"m-l3","level":"analyst","category":"Deduction","question":"Which cards must you turn over to test the rule?","options":["Triangle and 4","Triangle and 7","Circle and 4","All four cards"],"answer":"Triangle and 7","explanation":"Turn the triangle over to check for an even number. Turn 7 over to check that it does not have a triangle. A circle or a 4 cannot by itself disprove this one-way rule.","hint":"Look for a card that could disprove the rule.","tokens":[],"prompt":"Each card has a shape on one side and a number on the other. Rule: a triangle must have an even number on its other side. Visible faces: triangle, circle, 4, 7."},
{"id":"h-n1","level":"architect","category":"Number patterns","question":"What comes next?","options":["25","31","33","35"],"answer":"33","explanation":"The differences double: +1, +2, +4, +8, then +16. So 17 + 16 = 33.","hint":"The differences do not grow by a fixed amount.","tokens":["2","3","5","9","17","?"],"prompt":""},
{"id":"h-n2","level":"architect","category":"Number patterns","question":"What comes next?","options":["73","95","97","99"],"answer":"97","explanation":"Double each term and subtract 1: 4 → 7 → 13 → 25 → 49 → 97. Equivalently, the gaps double: 3, 6, 12, 24, 48.","hint":"Compare each number with twice the previous number.","tokens":["4","7","13","25","49","?"],"prompt":""},
{"id":"h-n3","level":"architect","category":"Number patterns","question":"What comes next?","options":["50","54","55","56"],"answer":"56","explanation":"The gaps are 3, 6, 10, and 15. Those gaps increase by 3, 4, 5, then 6, so the next gap is 21. Thus 35 + 21 = 56.","hint":"Look at the differences, then at how those differences change.","tokens":["1","4","10","20","35","?"],"prompt":""},
{"id":"h-v1","level":"architect","category":"Symbol patterns","question":"Which pair comes next?","options":["H16","I10","I16","J32"],"answer":"I16","explanation":"The letters advance by 2: A, C, E, G, I. The numbers double: 1, 2, 4, 8, 16.","hint":"Two independent rules are running at the same time.","tokens":["A1","C2","E4","G8","?"],"prompt":""},
{"id":"h-v2","level":"architect","category":"Symbol patterns","question":"Which pair comes next?","options":["5T","5U","5Y","6Z"],"answer":"5Y","explanation":"Square the number to get the letter position. 1² = 1 (A), 2² = 4 (D), 3² = 9 (I), 4² = 16 (P), and 5² = 25 (Y).","hint":"Convert each letter into its alphabet position.","tokens":["1A","2D","3I","4P","?"],"prompt":"Use A = 1, B = 2, …, Z = 26."},
{"id":"h-v3","level":"architect","category":"Symbol patterns","question":"What completes the third row?","options":["15","18","20","23"],"answer":"20","explanation":"Multiply the first number by one more than the second: 2 × (3 + 1) = 8; 4 × (2 + 1) = 12; 5 × (3 + 1) = 20.","hint":"Try multiplying, then adding the first number once more.","tokens":[],"prompt":"Use the same simple rule in every row.\n2, 3 → 8\n4, 2 → 12\n5, 3 → ?"},
{"id":"h-l1","level":"architect","category":"Deduction","question":"Which box contains the prize?","options":["Box A","Box B","Box C","No arrangement works."],"answer":"Box C","explanation":"If the prize were in A, the A and C labels would be true. If it were in B, the B and C labels would be true. In C, only B is true. So C is the only location with exactly one true label.","hint":"Try each possible location and count the true labels.","tokens":[],"prompt":"One prize is in one of three boxes. Exactly one label is true.\nA: “The prize is in A.”\nB: “The prize is not in A.”\nC: “The prize is not in C.”"},
{"id":"h-l2","level":"architect","category":"Deduction","question":"Which other sensor passes?","options":["P","Q","S","It cannot be determined."],"answer":"S","explanation":"If P and Q both passed, adding R would give at least three passes. So P and Q both fail. R and S must be the exactly two that pass.","hint":"Test the possibility that P and Q both pass.","tokens":[],"prompt":"Exactly two of P, Q, R, and S pass a check. P and Q have the same outcome. R passes."},
{"id":"h-l3","level":"architect","category":"Deduction","question":"What is the smallest possible sum?","options":["64","73","82","91"],"answer":"64","explanation":"Put the two smallest digits, 2 and 3, in the tens positions. The remaining digits contribute 5 + 9 = 14. The sum is 20 + 30 + 14 = 64, as in 25 + 39.","hint":"The tens positions matter ten times as much as the units positions.","tokens":[],"prompt":"Use each digit 2, 3, 5, and 9 exactly once to make two two-digit numbers. Add those two numbers."}
];
const $=(s,node=document)=>node.querySelector(s), $$=(s,node=document)=>[...node.querySelectorAll(s)];
const escape=text=>String(text).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const accessible=token=>({'↑':'Up arrow','→':'Right arrow','↓':'Down arrow','←':'Left arrow','◇':'Outlined diamond','●':'Filled circle','■':'Filled square','▲':'Filled triangle','?':'Missing item'}[token]||token);
const levels={explorer:['Explorer','Warm up'],analyst:['Analyst','Dig deeper'],architect:['Architect','Connect rules']};
const categories=['Number patterns','Symbol patterns','Deduction'],storeKey='sa-signal-sense-v1';
function readRecords(){try{const saved=JSON.parse(localStorage.getItem(storeKey)||'{}');return Object.fromEntries(Object.keys(levels).map(key=>[key,Number.isInteger(saved?.[key])&&saved[key]>=0&&saved[key]<=600?saved[key]:0]));}catch{return {explorer:0,analyst:0,architect:0};}}
let records=readRecords();
const shuffle=array=>{const out=[...array];for(let i=out.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[out[i],out[j]]=[out[j],out[i]];}return out;};
let level='explorer',deck=[],round=0,score=0,solved=0,streak=0,bestStreak=0,selected=null,answered=false,hinted=false,history=[],previousIds='';
const section=document.createElement('section');section.id='play';section.className='playground wrap';section.setAttribute('aria-labelledby','play-title');
section.innerHTML=`<div class="play-layout"><div class="play-intro"><p class="eyebrow">A short break</p><h2 id="play-title">Up for a few<br><span class="serif">puzzles?</span></h2><p>Try a round of Signal Sense. There are six puzzles, and you can take as long as you like.</p><p class="game-premise">Stuck on one? Ask for a hint, or skip ahead and read the answer.</p><div class="game-facts"><span>6 puzzles per round</span><span>3 difficulty levels</span><span>No timer</span></div><div class="game-privacy">Play without an account. Your best score stays in this browser. This is a reasoning game, not a validated IQ test.</div></div><div class="game-shell"><div class="game-top"><span class="game-brand"><span class="game-brand-icon" aria-hidden="true"></span>Signal Sense</span><span id="game-top-status">Six puzzles, at your pace</span></div><div class="game-body" id="game-body" tabindex="-1"></div><div class="game-footnote"><span>Reasoning practice, not an IQ score.</span><span id="game-bottom-status">No timer. Take your time.</span></div></div></div>`;
$('#approach').before(section);const body=$('#game-body');
function pulse(){if(document.documentElement.dataset.motion==='reduced'||!body.animate)return;body.animate([{opacity:.4,transform:'translateY(5px)'},{opacity:1,transform:'translateY(0)'}],{duration:230,easing:'ease-out'});}
function focusQuestion(){const heading=$('#game-question');if(!heading)return;heading.focus({preventScroll:true});const rect=heading.getBoundingClientRect();if(rect.top<$('.site-header').offsetHeight+16||rect.top>innerHeight-100)heading.scrollIntoView({behavior:'instant',block:'start'});}
function formatTokens(tokens,className='question-tokens'){if(!tokens.length)return '';return `<div class="${className}" role="group" aria-label="Pattern to solve">${tokens.map(token=>`<span class="game-token ${token==='?'?'unknown':''} ${token.length>2?'long':''}" aria-label="${escape(accessible(token))}"><span aria-hidden="true">${escape(token)}</span></span>`).join('')}</div>`;}
function intro(focus=false){
$('#game-top-status').textContent='Six puzzles, at your pace';$('#game-bottom-status').textContent='No timer. Take your time.';
body.innerHTML=`<h3 id="game-question" tabindex="-1">Ready to try?</h3><p>Choose a level below. Look for the simplest intended pattern. You’ll see the explanation after each answer.</p>${formatTokens(['2','6','12','20','?'],'game-example')}<fieldset class="level-selector"><legend>Choose your challenge</legend><div class="level-options">${Object.entries(levels).map(([key,words])=>`<label class="level-option"><input type="radio" name="difficulty" value="${key}" ${level===key?'checked':''}><span class="level-face">${words[0]}<small>${words[1]}</small></span></label>`).join('')}</div></fieldset><button type="button" id="game-start" class="game-primary game-start">Start a round <span aria-hidden="true">→</span></button><p class="game-result-note">100 points per correct answer. With a hint: 50. Take your time; speed does not affect your score. Skipped and incorrect answers score 0.</p><div class="game-round-meta"><span id="game-best">Best here: ${records[level]} / 600</span><button type="button" class="game-text-button" id="game-clear-records">Clear saved scores</button></div>`;
$$('input[name=difficulty]',body).forEach(input=>input.addEventListener('change',()=>{level=input.value;$('#game-best').textContent=`Best here: ${records[level]} / 600`;}));$('#game-start').addEventListener('click',start);
$('#game-clear-records').addEventListener('click',()=>{records={explorer:0,analyst:0,architect:0};try{localStorage.removeItem(storeKey);}catch{}$('#game-best').textContent='Saved scores cleared.';});if(focus)focusQuestion();pulse();}
function start(){deck=shuffle(categories.flatMap(category=>shuffle(BANK.filter(q=>q.level===level&&q.category===category)).slice(0,2)));if(deck.map(q=>q.id).join(',')===previousIds)deck.reverse();previousIds=deck.map(q=>q.id).join(',');round=score=solved=streak=bestStreak=0;history=[];renderQuestion();}
function renderQuestion(){selected=null;answered=false;hinted=false;const q=deck[round],options=shuffle(q.options);$('#game-top-status').textContent=`${levels[level][0]} · ${score} points`;$('#game-bottom-status').textContent='Take your time. There is no countdown.';const long=options.some(option=>option.length>26);
body.innerHTML=`<div class="game-stage-label">Puzzle ${round+1} of 6 · ${q.category}</div><div class="game-progress" aria-hidden="true">${Array.from({length:6},(_,i)=>`<span class="${i<round?'done':i===round?'current':''}"></span>`).join('')}</div><h3 class="game-question" id="game-question" tabindex="-1">${escape(q.question)}</h3>${q.prompt?`<div class="game-prompt" style="white-space:pre-line">${escape(q.prompt)}</div>`:''}${formatTokens(q.tokens)}<fieldset class="game-answers ${long?'long-answers':''}" id="game-answers"><legend class="sr-only">Choose one answer</legend>${options.map((option,i)=>`<label class="game-answer"><input type="radio" name="answer" value="${i}" aria-label="${escape(accessible(option))}"><span>${escape(option)}</span><span class="answer-mark" aria-hidden="true"></span></label>`).join('')}</fieldset><div id="game-hint" class="game-hint" hidden></div><div id="game-feedback" aria-live="polite" aria-atomic="true"></div><div class="game-actions" id="game-actions"><button class="game-primary" type="button" id="game-check" disabled>Check answer <span aria-hidden="true">→</span></button><button class="game-text-button" id="game-hint-button" type="button">Get a hint</button><button class="game-text-button" id="game-skip" type="button">Skip</button></div><div class="game-round-meta"><span id="game-round-score">${score} points · ${solved} solved</span><span>Best streak: ${bestStreak}</span></div>`;
$$('input[name=answer]',body).forEach(input=>input.addEventListener('change',()=>{if(answered)return;selected=options[Number(input.value)];$('#game-check').disabled=false;}));$('#game-check').addEventListener('click',()=>{if(selected!==null&&!answered)answer(false,options);});$('#game-skip').addEventListener('click',()=>{if(!answered)answer(true,options);});$('#game-hint-button').addEventListener('click',()=>{if(answered||hinted)return;hinted=true;const hint=$('#game-hint');hint.textContent=q.hint+' A correct answer is now worth 50 points.';hint.hidden=false;hint.setAttribute('role','status');$('#game-hint-button').disabled=true;$('#game-hint-button').textContent='Hint used';});focusQuestion();pulse();}
function answer(skipped,options){if(answered)return;answered=true;const q=deck[round],correct=!skipped&&selected===q.answer,earned=correct?(hinted?50:100):0;score+=earned;if(correct){solved++;streak++;bestStreak=Math.max(streak,bestStreak);}else streak=0;history.push({q,selected:skipped?null:selected,correct,hinted,skipped,earned});
$$('input[name=answer]',body).forEach(input=>{input.disabled=true;const value=options[Number(input.value)],label=input.closest('label');if(value===q.answer){label.classList.add('answer-correct');$('.answer-mark',label).textContent='✓ Correct';}else if(value===selected&&!skipped){label.classList.add('answer-wrong');$('.answer-mark',label).textContent='× Your pick';}});
const feedback=$('#game-feedback');feedback.className='game-feedback'+(correct?'':' incorrect');feedback.innerHTML=`<strong>${correct?`Correct. +${earned} points`:skipped?'Skipped. Here is the rule.':'Not this time. Here is the rule.'}</strong><p><strong>Answer: ${escape(accessible(q.answer))}.</strong> ${escape(q.explanation)}</p>`;
$('#game-actions').innerHTML=`<button class="game-primary" type="button" id="game-next">${round===5?'See my results':'Next puzzle'} <span aria-hidden="true">→</span></button>`;$('#game-next').addEventListener('click',()=>{if(round===5)results();else{round++;renderQuestion();}});$('#game-round-score').textContent=`${score} points · ${solved} solved`;$('#game-top-status').textContent=`${levels[level][0]} · ${score} points`;$('#game-next').focus({preventScroll:true});}
function results(){const oldBest=records[level];records[level]=Math.max(records[level],score);let stored=false;try{localStorage.setItem(storeKey,JSON.stringify(records));stored=true;}catch{}
const title=solved===6?'You got all six.':solved>=4?'Nicely done.':'That was a tricky set.';$('#game-top-status').textContent='Round complete';$('#game-bottom-status').textContent='Another round?';
body.innerHTML=`<div class="game-stage-label">${levels[level][0]} · Round complete</div><h3 id="game-question" class="game-question" tabindex="-1" style="margin-top:14px">${title}</h3><div class="score-layout"><div class="score-dial" style="--score:${solved/6*100}" aria-label="${solved} of 6 puzzles solved"><strong>${solved}<small> / 6</small></strong></div><div class="score-summary"><strong>${score} <span class="mono">/ 600 points</span></strong><p>Best streak: ${bestStreak} · Hints used: ${history.filter(h=>h.hinted).length}</p><p>${score>oldBest?'A new best for this level.':`Best on this level: ${records[level]} / 600.`}</p></div></div><p>These points describe this round, not your intelligence. Review the explanations, then try another set of puzzles.</p><div class="game-actions"><button class="game-primary" type="button" id="game-replay">Play another round <span aria-hidden="true">↻</span></button><button class="game-text-button" type="button" id="game-levels">Change level</button><button class="game-text-button" type="button" id="game-copy">Copy my result</button></div><div id="copy-status" class="copy-status" role="status"></div><details class="game-review"><summary>Review all six answers</summary>${history.map((item,i)=>`<div class="review-item"><strong>${i+1}. ${escape(item.q.question)} ${item.correct?'✓':'·'}</strong><p>${item.q.tokens.length?escape(item.q.tokens.map(accessible).join(' · ')):escape(item.q.prompt)}</p><p>Your answer: ${item.skipped?'Skipped':escape(accessible(item.selected))}. Correct answer: ${escape(accessible(item.q.answer))}. ${item.earned} points.</p><p>${escape(item.q.explanation)}</p></div>`).join('')}</details><p class="game-result-note">${stored?'Best scores are stored only in this browser. Clear them from the challenge start screen.':'Browser storage is unavailable. Your score is shown here but will not persist after this page closes.'} This is a reasoning game, not a validated IQ assessment or percentile ranking.</p>`;
$('#game-replay').addEventListener('click',start);$('#game-levels').addEventListener('click',()=>intro(true));$('#game-copy').addEventListener('click',async()=>{const text=`I solved ${solved}/6 puzzles in Signal Sense (${levels[level][0]}) and scored ${score}/600. A reasoning game, not an IQ test. Try it: https://akinyede.github.io/S-Akinyede/lab.html`,status=$('#copy-status');try{if(!navigator.clipboard?.writeText)throw new Error('Clipboard unavailable');await navigator.clipboard.writeText(text);status.textContent='Result copied. Share it wherever you like.';}catch{status.textContent='Select and copy your result below:';const field=document.createElement('textarea');field.readOnly=true;field.className='score-fallback';field.setAttribute('aria-label','Result to copy');field.value=text;status.append(field);field.focus();field.select();}});focusQuestion();pulse();}
intro();if(location.hash==='#play')requestAnimationFrame(()=>section.scrollIntoView({behavior:'instant',block:'start'}));document.documentElement.dataset.interactive='ready';
})();
